Build with Clang
Hopefully fixes:
```
In file included from D:/a/build-llvm/build-llvm/llvm-project/libunwind/src/UnwindCursor.hpp:73,
                 from D:/a/build-llvm/build-llvm/llvm-project/libunwind/src/libunwind.cpp:22:
D:/a/build-llvm/build-llvm/llvm-project/libunwind/src/RWMutex.hpp: In member function 'bool libunwind::RWMutex::lock_shared()':
D:/a/build-llvm/build-llvm/llvm-project/libunwind/src/RWMutex.hpp:42:5: error: 'AcquireSRWLockShared' was not declared in this scope
     AcquireSRWLockShared(&_lock);
     ^~~~~~~~~~~~~~~~~~~~
```
which was hit in the Windows build.

Disable fail-fast so one build failing won't kill the others

Add Ninja build command to matrix config

Add OS name to artifact name